### ISSUE TITLE
Frame for 概 OK?

### ISSUE THREAD

**Issue by rauschma** [rouseabout/heisig#2]
This is the XML:

```xml
<frame xsi:type="character" number="1159" character="概" keyword="approximate" pos="adj.">
<strokes>13</strokes>
<p><cite>root</cite> ... <cite>waitress</cite>. <info keyword="tree"/><info keyword="since"/><count/></p>
</frame>
```

* I suspect that “root” and “waitress” are wrong in some way. The components of “approximate” are “tree” and “since”. Should the `<info>` elements become `<cite>` elements? I don’t fully understand how `<info>` works, however.

**Comment by rouseabout** [comment]
According to Heisig this character can be interpreted two way: **root** and **waitress**, or **tree** and **since**. Both are valid interpretation of the character.

In his book, he gives no specific story, just "_Root .. waitress._" leaving it up to the reader to make up a story. He also says "_It is also possible to divide the character up into tree and since._" I use `<cite>` tags for marking up the story, and use `<info>` tags for other guidance..

I don't believe there is a problem here. Thanks for using my database!

**Comment by rauschma** [comment]
> I don't believe there is a problem here.

Right, my bad:

* My version of “Remembering Simplified Hanzi” only mentions “Tree...since”.
* But “Root...waitress” does indeed work just as well. Due to a different system I had used before RSH, I incorrectly thought “root” = 本.

Apologies for the noise!
